cmake_minimum_required(VERSION 3.16)
project(wc_estimation)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(angles REQUIRED)
find_package(robot_localization REQUIRED)
find_package(Eigen3 REQUIRED)
add_executable(wc_rl_worker src/rl_worker.cpp)
ament_target_dependencies(wc_rl_worker rclcpp robot_localization angles)
target_link_libraries(wc_rl_worker Eigen3::Eigen ${robot_localization_LIBRARIES})
target_compile_options(wc_rl_worker PRIVATE -Wall -Wextra -Wpedantic)
install(TARGETS wc_rl_worker RUNTIME DESTINATION lib/${PROJECT_NAME})
ament_package()
