#!/usr/bin/env python3
"""Run the foreground mapping app without requiring a sourced Python shell."""
from pathlib import Path
import os
import sys

PROJECT = Path('/home/nvidia/wheelchair')
os.environ['PYTHONNOUSERSITE']='1'
if not sys.flags.no_user_site:
    os.execv(sys.executable,[sys.executable,'-s',__file__,*sys.argv[1:]])
sys.path.insert(0, str(PROJECT / 'src'))

from wc_runtime.mapping_app import main


if __name__ == '__main__':
    os.chdir(PROJECT)
    sys.exit(main(project_root=PROJECT))
